version: '3.8'
services:
  mysql:
    image: mysql:lts
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=REMSFAL

  grafana:
    networks:
      - remsfal
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - remsfal
    ports:
      - '9090:9090'

  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    ports:
      - "8081:8080"
    environment:
      - INIT_WITH_DEMO_DATA=false 
      - CAMUNDA_BPM_RUN_EXAMPLE_ENABLED=false 
    volumes:
      - ./processes:/camunda/configuration/resources/processes
    networks:
      - remsfal

networks:
  remsfal:
    driver: bridge